// Golden-corpus parity test for the IndexTTS text normalizers.
//
// tests/unittests/assets/index_tts_tn_corpus.tsv contains one case per line:
//   route<TAB>input<TAB>expected[<TAB>flag]
// where `expected` was generated by the official IndexTTS2.5 Python front-end
// (clean_pattern char map -> TextNormalizer.normalize, glossary disabled).
// `flag` may carry KNOWN:<reason> for accepted divergences (reported, not
// failed) or OFFICIAL_ROUTE=<lang> when the official use_chinese() routing
// differs from the C++ Han-character routing.
//
// Regenerate goldens on a machine with the official repo + venv:
//   python tn_golden_generate.py corpus.tsv corpus_golden.tsv
// (the generator is kept out of the repo; see INDEXTTS_TN_PARITY_HANDOFF.md)

#include "engine/framework/text/chinese_normalization.h"
#include "engine/framework/text/text_normalization.h"

#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace {

struct Case {
    std::string route;
    std::string input;
    std::string expected;
    std::string flag;
};

std::vector<std::string> split_tab(const std::string & line) {
    std::vector<std::string> parts;
    size_t begin = 0;
    for (;;) {
        const size_t pos = line.find('\t', begin);
        if (pos == std::string::npos) {
            parts.push_back(line.substr(begin));
            break;
        }
        parts.push_back(line.substr(begin, pos - begin));
        begin = pos + 1;
    }
    return parts;
}

std::string normalize(const Case & c) {
    if (c.route == "zh") {
        return engine::text::normalize_chinese_text(
            c.input, engine::text::ChineseTextNormalizationTarget::IndexTTS);
    }
    // Matches IndexTTS2TextTokenizer::normalize_english for the v2.5 variant.
    engine::text::EnglishTextNormalizationOptions options;
    options.expand_common_contractions = true;
    options.index_tts_punctuation = true;
    options.uppercase_ascii = false;
    options.verbalize_symbols = true;
    return engine::text::normalize_english_text(c.input, options);
}

}  // namespace

int main() {
    std::ifstream in(std::string(ENGINE_TEST_ASSET_ROOT) + "/index_tts_tn_corpus.tsv");
    if (!in) {
        std::cerr << "failed to open index_tts_tn_corpus.tsv under " << ENGINE_TEST_ASSET_ROOT << "\n";
        return 1;
    }

    int total = 0;
    int failed = 0;
    int known = 0;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line.front() == '#') {
            continue;
        }
        const auto parts = split_tab(line);
        if (parts.size() < 3) {
            std::cerr << "malformed corpus line: " << line << "\n";
            return 1;
        }
        Case c{parts[0], parts[1], parts[2], parts.size() > 3 ? parts[3] : ""};
        ++total;
        const std::string actual = normalize(c);
        if (actual == c.expected) {
            continue;
        }
        const bool is_known = c.flag.rfind("KNOWN:", 0) == 0;
        std::cout << (is_known ? "KNOWN-DIFF" : "MISMATCH  ") << " [" << c.route << "] " << c.input
                  << "\n  expected: " << c.expected << "\n  actual:   " << actual << "\n";
        if (is_known) {
            ++known;
        } else {
            ++failed;
        }
    }

    std::cout << "index_tts_tn_corpus_test: " << total << " cases, " << failed << " mismatches, " << known
              << " known diffs\n";
    return failed == 0 ? 0 : 1;
}
